// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIErrorResponse Api error response
//
// swagger:model ApiErrorResponse
type APIErrorResponse struct {

	// code
	Code int64 `json:"code,omitempty"`

	// a (key, value) map.
	Details interface{} `json:"details,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this Api error response
func (m *APIErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api error response based on context it is used
func (m *APIErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIErrorResponse) UnmarshalBinary(b []byte) error {
	var res APIErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
