// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CartItemUpdateRequest cart item update request
//
// swagger:model CartItemUpdateRequest
type CartItemUpdateRequest struct {

	// quantity
	Quantity int64 `json:"quantity,omitempty"`
}

// Validate validates this cart item update request
func (m *CartItemUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cart item update request based on context it is used
func (m *CartItemUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CartItemUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CartItemUpdateRequest) UnmarshalBinary(b []byte) error {
	var res CartItemUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
