// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderRequest order request
//
// swagger:model OrderRequest
type OrderRequest struct {

	// cart Id
	// Required: true
	// Format: uuid
	CartID *strfmt.UUID `json:"cartId"`
}

// Validate validates this order request
func (m *OrderRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCartID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderRequest) validateCartID(formats strfmt.Registry) error {

	if err := validate.Required("cartId", "body", m.CartID); err != nil {
		return err
	}

	if err := validate.FormatOf("cartId", "body", "uuid", m.CartID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order request based on context it is used
func (m *OrderRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderRequest) UnmarshalBinary(b []byte) error {
	var res OrderRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
